### ISSUE TITLE
Hello, everyone. When i build visqol, why the warning saying Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/4ce3e4da2e21ae4dfcee9366415e55f408c884ec.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found

### ISSUE THREAD

**Issue by DingWeiPeng** [google/visqol#106]
D:\visqol\visqol>bazel build :visqol -c opt
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/4ce3e4da2e21ae4dfcee9366415e55f408c884ec.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
DEBUG: C:/users/administrator/_bazel_administrator/gtvto7rk/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'pybind11_abseil' because it already exists.
DEBUG: C:/users/administrator/_bazel_administrator/gtvto7rk/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: C:/users/administrator/_bazel_administrator/gtvto7rk/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/users/administrator/_bazel_administrator/gtvto7rk/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: Repository local_execution_config_python instantiated at:
  D:/visqol/visqol/WORKSPACE:104:11: in <toplevel>
  C:/users/administrator/_bazel_administrator/gtvto7rk/external/org_tensorflow/tensorflow/workspace2.bzl:928:19: in workspace
  C:/users/administrator/_bazel_administrator/gtvto7rk/external/org_tensorflow/tensorflow/workspace2.bzl:88:27: in _tf_toolchains
  C:/users/administrator/_bazel_administrator/gtvto7rk/external/org_tensorflow/tensorflow/tools/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
  C:/users/administrator/_bazel_administrator/gtvto7rk/external/org_tensorflow/tensorflow/tools/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
Repository rule local_python_configure defined at:
  C:/users/administrator/_bazel_administrator/gtvto7rk/external/org_tensorflow/third_party/py/python_configure.bzl:279:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/users/administrator/_bazel_administrator/gtvto7rk/external/org_tensorflow/third_party/py/python_configure.bzl", line 213, column 33, in _create_local_python_repository
                python_lib = _get_python_lib(repository_ctx, python_bin)
        File "C:/users/administrator/_bazel_administrator/gtvto7rk/external/org_tensorflow/third_party/py/python_configure.bzl", line 130, column 21, in _get_python_lib
                result = execute(repository_ctx, [python_bin, "-c", cmd])
        File "C:/users/administrator/_bazel_administrator/gtvto7rk/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed

ERROR: D:/visqol/visqol/WORKSPACE:104:11: fetching local_python_configure rule //external:local_execution_config_python: Traceback (most recent call last):
        File "C:/users/administrator/_bazel_administrator/gtvto7rk/external/org_tensorflow/third_party/py/python_configure.bzl", line 213, column 33, in _create_local_python_repository
                python_lib = _get_python_lib(repository_ctx, python_bin)
        File "C:/users/administrator/_bazel_administrator/gtvto7rk/external/org_tensorflow/third_party/py/python_configure.bzl", line 130, column 21, in _get_python_lib
                result = execute(repository_ctx, [python_bin, "-c", cmd])
        File "C:/users/administrator/_bazel_administrator/gtvto7rk/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed

WARNING: errors encountered while analyzing target '//:visqol': it will not be built
INFO: Analyzed target //:visqol (0 packages loaded, 0 targets configured).
INFO: Found 0 targets...
ERROR: command succeeded, but not all targets were analyzed
INFO: Elapsed time: 0.601s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
FAILED: Build did NOT complete successfully

**Comment by DingWeiPeng** [comment]
And then the errors happen, saying ERROR: D:/visqol/visqol/WORKSPACE:104:11: fetching local_python_configure rule //external:local_execution_config_python: Traceback (most recent call last):

**Comment by 2980308805** [comment]
@DingWeiPeng have u done this problem?

**Comment by q1163931796** [comment]
> 然后错误发生，说 ERROR： D：/visqol/visqol/WORKSPACE：104：11： fetching local_python_configure rule //external：local_execution_config_python： Traceback （最近一次调用最后）：



> 然后错误发生，说 ERROR： D：/visqol/visqol/WORKSPACE：104：11： fetching local_python_configure rule //external：local_execution_config_python： Traceback （最近一次调用最后）：

您好，请问您这个问题是怎么解决的

**Comment by philippgrundhuber** [comment]
You can solve the problem by changing following:
in the file WORKSPACE change the url in line 174 to
urls = ["https://sourceforge.net/projects/arma/files/retired/armadillo-9.900.1.tar.xz"],

The armadillo packaged got moved

**Comment by EPIGP** [comment]
> You can solve the problem by changing following: in the file WORKSPACE change the url in line 174 to urls = ["https://sourceforge.net/projects/arma/files/retired/armadillo-9.900.1.tar.xz"],
> 
> The armadillo packaged got moved

please read this link:
https://github.com/google/visqol/issues/117#issuecomment-2407779701
